swagger: "2.0"
info:
  description: "REST API for draughts"
  version: "0.0.1"
  title: "SwaggerDraughts"
  contact:
    email: "jj358817@icm.edu.pl"
  license:
    name: "GNU GPL v3"
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
host: "localhost"
basePath: "/v0"
schemes:
- "https"
- "http"
paths:
  /board:
    get:
      summary: "Get board state"
      description: ""
      operationId: "getCurrentBoardState"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            items:
              $ref: "#/definitions/Board"
    post:
      summary: "Computer move"
      description: ""
      operationId: "computerMove"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "board"
        description: "State of the board"
        required: true
        schema:
          $ref: "#/definitions/Board"
      responses:
        "200":
          description: "successful operation"
          schema:
            items:
              $ref: "#/definitions/Board"
definitions:
  Board:
    required:
    - "pieces"
    type: "object"
    properties:
      pieces:
        type: "array"
        items:
          type: "array"
          items:
            $ref: "#/definitions/Field"
  Field:
    type: "object"
    required:
    - "type"
    - "X"
    - "Y"
    properties:
      type:
        type: "string"
        enum:
        - "white_man"
        - "white_king"
        - "black_man"
        - "black_king"
        - "empty"
      X:
        type: "integer"
      Y:
        type: "integer"