openapi: 3.0.1
info:
  title: SwaggerDraughts
  description: REST API for draughts
  contact:
    email: jj358817@icm.edu.pl
  license:
    name: GNU GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.html
  version: 0.0.1
servers:
- url: http://localhost/v0
paths:
  /board:
    get:
      summary: Get board state
      operationId: getCurrentBoardState
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
    post:
      summary: Computer move
      operationId: computerMove
      requestBody:
        description: State of the board
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Board'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
      x-codegen-request-body-name: board
components:
  schemas:
    Board:
      required:
      - pieces
      type: object
      properties:
        pieces:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/Field'
    Field:
      required:
      - X
      - Y
      - type
      type: object
      properties:
        type:
          type: string
          enum:
          - white_man
          - white_king
          - black_man
          - black_king
          - empty
        X:
          type: integer
        Y:
          type: integer
