/**
 * SwaggerDraughts
 * REST API for draughts
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jj358817@icm.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Piece { 
    color: Piece.ColorEnum;
    type: Piece.TypeEnum;
    X: number;
    Y: number;
}
export namespace Piece {
    export type ColorEnum = 'white' | 'black';
    export const ColorEnum = {
        White: 'white' as ColorEnum,
        Black: 'black' as ColorEnum
    };
    export type TypeEnum = 'man' | 'king';
    export const TypeEnum = {
        Man: 'man' as TypeEnum,
        King: 'king' as TypeEnum
    };
}
