/**
 * SwaggerDraughts
 * REST API for draughts
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jj358817@icm.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Field } from './field';


export class Board {
  readonly pieces: Array<Array<Field>>;
  constructor(dimension: number) {
    // this.pieces = new Array<Array<Field>>();
    let array = Array(dimension)
    let x = array.map(y => {
      return array.map(x => {
        if (y < 3 && x + y % 2 == 1) {
          return new Field(x, y, Field.TypeEnum.WhiteMan)
        }
        else if (y >= dimension - 3 && x + y % 2 == 1) {
          return new Field(x, y, Field.TypeEnum.BlackMan)
        }
        else {
          return new Field(x, y, Field.TypeEnum.Empty)
        }
      })
    });
    this.pieces = x;
  }

}
