/**
 * SwaggerDraughts
 * REST API for draughts
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jj358817@icm.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Field } from './field';


export class Board { 
    pieces: Array<Array<Field>>;
    constructor(dimension: number) {
      this.pieces = new Array<Array<Field>>();
      let array = Array(dimension);
      for(let x = 0; x < dimension; x++) {
        let row = new Array<Field>();
        for(let y = 0; y < dimension; y++) {
          row.push(new Field(x, y));
        }
        this.pieces.push(row);
      }
    } 

}
