/**
 * SwaggerDraughts
 * REST API for draughts
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jj358817@icm.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class Field {
  constructor(x, y, type: Field.TypeEnum) {
    this.type = type;
    this.X = x;
    this.Y = y;
    switch ((this.X + this.Y) % 2) {
      case 0:
        this.color = Field.ColorEnum.Black;
      case 1:
        this.color = Field.ColorEnum.White;
    }
  }
  type: Field.TypeEnum;
  color: Field.ColorEnum;
  X: number;
  Y: number;

  public getCssClass() {
    return "field " + this.color + "-field " + this.type;
  }

  public getIcon() {
    switch (this.type) {
      case Field.TypeEnum.WhiteKing:
        return "/assets/icons/white_king.png"
      case Field.TypeEnum.WhiteMan:
        return "/assets/icons/white_man.png"
      case Field.TypeEnum.BlackKing:
        return "/assets/icons/black_king.png"
      case Field.TypeEnum.BlackMan:
        return "/assets/icons/black_man.png"
      case Field.TypeEnum.Empty:
        return ""
    }
  }
}
export namespace Field {
  export type TypeEnum = 'white_man' | 'white_king' | 'black_man' | 'black_king' | 'empty';
  export const TypeEnum = {
    WhiteMan: 'white-man' as TypeEnum,
    WhiteKing: 'white-king' as TypeEnum,
    BlackMan: 'black-man' as TypeEnum,
    BlackKing: 'black-king' as TypeEnum,
    Empty: 'empty' as TypeEnum
  };
  export type ColorEnum = 'white' | 'black';
  export const ColorEnum = {
    White: 'white' as ColorEnum,
    Black: 'black' as ColorEnum
  };
}
