/**
 * SwaggerDraughts
 * REST API for draughts
 *
 * OpenAPI spec version: 0.0.1
 * Contact: jj358817@icm.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Field { 
    type: Field.TypeEnum;
    X: number;
    Y: number;
}
export namespace Field {
    export type TypeEnum = 'white_man' | 'white_king' | 'black_man' | 'black_king' | 'empty';
    export const TypeEnum = {
        WhiteMan: 'white_man' as TypeEnum,
        WhiteKing: 'white_king' as TypeEnum,
        BlackMan: 'black_man' as TypeEnum,
        BlackKing: 'black_king' as TypeEnum,
        Empty: 'empty' as TypeEnum
    };
}
