---
swagger: "2.0"
info:
  description: "REST API for draughts"
  version: "0.0.1"
  title: "SwaggerDraughts"
  contact:
    email: "jj358817@icm.edu.pl"
  license:
    name: "GNU GPL v3"
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
host: "localhost"
basePath: "/v0"
schemes:
- "https"
- "http"
paths:
  /board:
    get:
      summary: "Get board state"
      description: ""
      operationId: "getCurrentBoardState"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema: {}
          x-responseId: "SuccessfulOperation"
          x-uppercaseResponseId: "SUCCESSFUL_OPERATION"
          uppercase_operation_id: "GET_CURRENT_BOARD_STATE"
          uppercase_data_type: "OBJECT"
          producesJson: true
      operation_id: "get_current_board_state"
      uppercase_operation_id: "GET_CURRENT_BOARD_STATE"
      path: "/board"
      PATH_ID: "BOARD"
      hasPathParams: false
      HttpMethod: "Get"
    post:
      summary: "Computer move"
      description: ""
      operationId: "computerMove"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "board"
        description: "State of the board"
        required: true
        schema:
          $ref: "#/definitions/Board"
        uppercase_data_type: "BOARD"
        refName: "Board"
        formatString: "{:?}"
        example: "???"
        model_key: "Field"
        uppercase_operation_id: "COMPUTER_MOVE"
        consumesJson: true
      responses:
        "200":
          description: "successful operation"
          schema: {}
          x-responseId: "SuccessfulOperation"
          x-uppercaseResponseId: "SUCCESSFUL_OPERATION"
          uppercase_operation_id: "COMPUTER_MOVE"
          uppercase_data_type: "OBJECT"
          producesJson: true
      operation_id: "computer_move"
      uppercase_operation_id: "COMPUTER_MOVE"
      path: "/board"
      PATH_ID: "BOARD"
      hasPathParams: false
      HttpMethod: "Post"
      noClientExample: true
definitions:
  Board:
    type: "object"
    required:
    - "pieces"
    properties:
      pieces:
        type: "array"
        items:
          type: "array"
          items:
            $ref: "#/definitions/Field"
    upperCaseName: "BOARD"
  Field:
    type: "object"
    required:
    - "X"
    - "Y"
    - "type"
    properties:
      type:
        type: "string"
        enum:
        - "white_man"
        - "white_king"
        - "black_man"
        - "black_king"
        - "empty"
      X:
        type: "integer"
      Y:
        type: "integer"
    upperCaseName: "FIELD"
